name: ah_flutter_sdk
description: "A Flutter SDK for Arrowhead voice-based AI agent calls."
version: 0.0.1

environment:
  sdk: ^3.11.5
  flutter: ">=3.10.0"

dependencies:
  daily_flutter: ^0.37.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
